// Crea Usuario
POST http://localhost:4001/api/auth/new HTTP/1.1
Content-Type: application/json

{
  "nombres": "Sonia Marilyn",
  "apellidos": "Poma Quispe",
  "email": "senia@gmail.com",
  "password": "Senia123"
}

###
// Loguear usuario
POST http://localhost:4001/api/auth HTTP/1.1
Content-Type: application/json

{
  "email": "senia@gmail.com",
  "password": "Senia123"
}
//{
  //"email": "miguel@gmail.com",
  //"password": "123456"
//}


###
// Revalidar Token
GET  http://localhost:4001/api/auth/renew HTTP/1.1
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MzIxNDk2ODIwZDMyNmQyZTRhOWRjN2MiLCJub21icmVzIjoiU29uaWEgTWFyaWx5biIsImlhdCI6MTY2MzE5Nzg1OSwiZXhwIjoxNjYzMjA1MDU5fQ.8UiehBmvVvlVuEqF1Hd-djcXrVmAuKVcEH7PuPyLFp4