// Crea Usuario
POST http://localhost:4001/api/auth/new HTTP/1.1
Content-Type: application/json

{
  "name": "Sonia Poma",
  "email": "seniapq@gmail.com",
  "password": "123456"
}

###
// Loguear usuario
POST http://localhost:4001/api/auth/ HTTP/1.1
Content-Type: application/json

{
  "email": "miguel@gmail.com",
  "password": "123456"
}


###
// Revalidar Token
GET  http://localhost:4001/api/auth/ HTTP/1.1
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MzA1OGY0MWI4MmFmOGZkY2M2ZmU1ODgiLCJuYW1lIjoiTWlndWVsIEFuZ2VsIiwiaWF0IjoxNjYxMzE1NTUxLCJleHAiOjE2NjEzMjI3NTF9.uc24CznQhtLW3AVH05sIogw3mjM8DwOCtygFm3dOwDU 